//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Admin
    {
        public int Admin_Id { get; set; }
        public string Admin_FullName { get; set; }
        public string Admin_UserName { get; set; }
        public string Admin_Password { get; set; }
        public Nullable<int> Admin_ContactNo { get; set; }
    }
}
