//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Drug_History
    {
        public int Drug_Pk { get; set; }
        public string Drug_Name { get; set; }
        public string Drug_Code { get; set; }
        public Nullable<int> Drug_Qty { get; set; }
        public Nullable<int> Student_History_Pk { get; set; }
    
        public virtual MC_Student_History MC_Student_History { get; set; }
    }
}
