//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Ddrug_Stoke
    {
        public int Drug_Stoke_pk { get; set; }
        public string Drug_Code { get; set; }
        public string Drug_Name { get; set; }
        public Nullable<System.DateTime> Recevive_Date { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantitty { get; set; }
    }
}
