//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Drug_Balance
    {
        public int Drug_Blance_PK { get; set; }
        public string Drug_Code { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
