//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MC_Student()
        {
            this.MC_Student_History = new HashSet<MC_Student_History>();
        }
    
        public int Student_Pk { get; set; }
        public string Student_Name { get; set; }
        public string Student_RegNo { get; set; }
        public Nullable<int> Student_Age { get; set; }
        public string Student_NicNo { get; set; }
        public string Student_Gender { get; set; }
        public Nullable<System.DateTime> Student_DateOfBirth { get; set; }
        public string Student_Faculty { get; set; }
        public Nullable<int> Student_Year { get; set; }
        public string Student_Rational { get; set; }
        public Nullable<int> Student_FamilyMembers { get; set; }
        public string Student_FatherName { get; set; }
        public string Student_MotherName { get; set; }
        public string Student_Password { get; set; }
        public Nullable<int> Has_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MC_Student_History> MC_Student_History { get; set; }
    }
}
