//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MC_Student_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MC_Student_History()
        {
            this.MC_Drug_History = new HashSet<MC_Drug_History>();
        }
    
        public int Student_History_Pk { get; set; }
        public int Student_Pk { get; set; }
        public string Disease { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Medical { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MC_Drug_History> MC_Drug_History { get; set; }
        public virtual MC_Student MC_Student { get; set; }
    }
}
