//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabraMedicalCenter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalcentreEntities : DbContext
    {
        public MedicalcentreEntities()
            : base("name=MedicalcentreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MC_Admin> MC_Admin { get; set; }
        public virtual DbSet<MC_Ddrug_Stoke> MC_Ddrug_Stoke { get; set; }
        public virtual DbSet<MC_Drug_Balance> MC_Drug_Balance { get; set; }
        public virtual DbSet<MC_Drug_History> MC_Drug_History { get; set; }
        public virtual DbSet<MC_Student> MC_Student { get; set; }
        public virtual DbSet<MC_Student_History> MC_Student_History { get; set; }
    }
}
